const profiles = [
        {
        id: 1,
        name: "Pablo Grillo",
        role: "TL Frontend Developer",
        linkedInUrl: "https://www.linkedin.com/in/pablo-grillo/",
        githubUrl: "https://github.com/GrilloPablo",
        image: 'only1',
        },
        {
        id: 2,
        name: "Ezequiel Stom",
        role: "Frontend Developer",
        linkedInUrl: "https://www.linkedin.com/in/ezequielstom/",
        githubUrl: "https://github.com/ezestom",
        image: 'only2',
        },
        {
        id: 3,
        name: "Román Díaz",
        role: "QA Technical Lead",
        linkedInUrl: "https://www.linkedin.com/in/romanadriel/",
        githubUrl: "https://github.com/RomanAdriel/",
        image: 'only3',
        },
        {
        id: 4,
        name: "Marcos Garlot",
        role: "UX/UI Designer",
        linkedInUrl: "https://www.linkedin.com/in/marcos-garlot-82633b1b5",
        githubUrl: "https://github.com/MarcosGarlot",
        image: 'only4',
        },
        {
        id: 5,
        name: "Daniel Choque",
        role: "TL BBDD Developer",
        linkedInUrl: "https://www.linkedin.com/in/dani-choque",
        githubUrl: "https://github.com/danielChoque-1",
        image: 'only5',
        },
        {
        id: 6,
        name: "Lucas Bonaffini",
        role: "Scrum Master",
        linkedInUrl: "https://www.linkedin.com/in/lucasbonaffini/",
        githubUrl: "https://github.com/lucasbonaffini",
        image: 'only6',
        },
        {
        id: 7,
        name: "Franco Barrera",
        role: "TL Backend Developer",
        linkedInUrl: "https://www.linkedin.com/in/francojulianb/",
        githubUrl: "https://gitlab.ctd.academy/ctd/hispanos/proyecto-integrador-1/proyecto-integrador-0723/0222pt-c5/equipo-06",
        image: 'only7',
        },
        {
        id: 8,
        name: "Noelia Zurbriggen",
        role: "Comodin Developer",
        linkedInUrl: " www.linkedin.com/in/noelia-zurbriggen",
        githubUrl: "https://gitlab.ctd.academy/ctd/hispanos/proyecto-integrador-1/proyecto-integrador-0723/0222pt-c5/equipo-06",
        image: 'only8',
        },
        {
        id: 9,
        name: "Juan Pablo Cappelletti",
        role: "TL DevOps Engineer",
        linkedInUrl: "www.linkedin.com/in/juan-pablo-cappelletti",
        githubUrl: "https://github.com/cappellettiJP",
        image: 'only9',
        },
    ];
    
export default profiles;